on:
    push:
    pull_request_target:

name: RHEL with GitHub Runners

permissions:
  contents: read
  id-token: write

jobs:
    test:
        runs-on: ubuntu-latest
        container: redhat/ubi9:latest
        env:
            SMDEV_CONTAINER_OFF: 1 
        steps:
            - name: Install a non-UBI shipped package - should fail
              run: |
                dnf install -y kernel-devel || echo "failed as expected"

            - name: Get RHEL subscription
              shell: bash
              run: |
                idtoken=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://rhel-issuer" | python3 -c 'import json; import sys; print(json.loads(sys.stdin.read())["value"])')
                result=$(curl -H "Authorization: Bearer $idtoken" https://8yblh00n16.execute-api.us-east-2.amazonaws.com/issue -X POST)
                error=$(echo $result | python3 -c 'import json; import sys; print(json.loads(sys.stdin.read())["error"])')
                echo "Error: $error"
                orgid=$(echo $result | python3 -c 'import json; import sys; print(json.loads(sys.stdin.read())["org_id"])')
                activation_key=$(echo $result | python3 -c 'import json; import sys; print(json.loads(sys.stdin.read())["activation_key"])')
                echo "::add-mask::$orgid"
                echo "::add-mask::$activation_key"
                
                subscription-manager register --org=$orgid --activationkey=$activation_key

            - name: Install a non-UBI shipped package - should succeed
              run: |
                dnf install -y kernel-devel
